spring:
  application:
    name: DevTracker API
  profiles:
    active: dev

server:
  port: 8081

app:
  name: DevTracker API
  cors:
    allowed-origin: http://localhost:5173
  jwt:
    # 256-bit Hexadecimal secret key for HS256 algorithm
    secret: 9a2f6c9d3e8b4a7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d
    # Expiry timings in milliseconds
    access-expiration: 900000 # 15 minutes
    refresh-expiration: 604800000 # 7 days
